import type { AuthorizedScope } from '../policy/EgressPolicyContracts.js';
import type { SafeActiveReconObservation } from './ActiveReconContracts.js';
import type { VerifiedAuthorizationDecision } from '../../authorization/VerifiedAuthorizationDecisionContracts.js';
import type { AuthorizedActiveReconRequestLineage } from '../../lineage/AuthorizedExecutionLineageContracts.js';

export type ActiveReconOriginRunVersion = 'active-recon-origin-run/v0';

export type ActiveReconOriginProbeSelection =
  | {
      family: 'document';
      probe: 'http.robots.inspect' | 'http.security_txt.inspect';
    };

/**
 * The canonical type for active origin run execution.
 * v1 is required for new executions (runtime enforcement).
 */
export type ActiveReconOriginRunRequest = {
  contractVersion: 'active-recon-origin-run/v1';
  requestId?: string;
  evaluatedAt: string;

  /** Runtime-established authorization decision. Plain lookalikes are rejected. */
  verifiedAuthorizationDecision: VerifiedAuthorizationDecision;

  origin: string;
  probes: ActiveReconOriginProbeSelection[];
};


export type ActiveReconOriginRunProbeResult = {
  safeProbeIndex: string;

  family: 'document';

  safeKind:
    | 'http.robots.inspect'
    | 'http.security_txt.inspect'
    | 'unknown';

  status:
    | 'planned'
    | 'completed'
    | 'blocked'
    | 'candidate'
    | 'failed';

  target: {
    normalizedOrigin?: string;
    safeDisplayUrl?: string;
  };

  observations: SafeActiveReconObservation[];

  error?: {
    code:
      | 'authorization_not_confirmed'
      | 'invalid_origin'
      | 'origin_out_of_scope'
      | 'unsupported_probe'
      | 'empty_probe_set'
      | 'planning_failed'
      | 'runner_failed'
      | 'adapter_missing'
      | 'adapter_failed'
      | 'policy_blocked'
      | 'policy_candidate'
      | 'batch_preflight_aborted';
    message: string;
  };
};

export type ActiveReconOriginRunError = {
  code:
    | 'authorization_not_confirmed'
    | 'invalid_origin'
    | 'origin_out_of_scope'
    | 'unsupported_probe'
    | 'empty_probe_set'
    | 'planning_failed'
    | 'runner_failed';
  message: string;
};

export type ActiveReconOriginRunResultVersion = 'active-recon-origin-run-result/v0';

export type ActiveReconOriginRunResult = {
  contractVersion: ActiveReconOriginRunResultVersion;

  runId: string; // generated by service, never caller-provided

  status: 'completed' | 'partial' | 'failed';
  disposition: import('./ActiveReconDocumentProbeRunContracts.js').ActiveReconBatchDisposition;

  normalizedOrigin?: string;

  requestedProbeCount: number;
  plannedProbeCount: number;
  completedProbeCount: number;
  blockedProbeCount: number;
  candidateProbeCount: number;
  failedProbeCount: number;

  runErrors: ActiveReconOriginRunError[];

  probes: ActiveReconOriginRunProbeResult[];

  observations: SafeActiveReconObservation[];

  classification: {
    finding: false;
    evidence: false;
    vulnerability: false;
    riskClaim: false;
  };
};

/**
 * Pure semantic derivation for the terminal run status based strictly on counts.
 * M39 uses this to determine if a run is completed, partial, or failed.
 */
export function deriveActiveReconRunStatus(
  plannedProbeCount: number,
  completedProbeCount: number
): 'completed' | 'partial' | 'failed' {
  if (completedProbeCount === plannedProbeCount && plannedProbeCount > 0) {
    return 'completed';
  } else if (completedProbeCount > 0) {
    return 'partial';
  } else {
    return 'failed';
  }
}
