import type { ActiveReconRunDetailView } from './ActiveReconRunReadModelContracts.js';
import type {
  ActiveReconRunSafeReportSnapshot,
  ActiveReconRunSafeReportSection
} from './ActiveReconRunSafeReportContracts.js';

export function buildActiveReconRunSafeReportSnapshot(
  detail: ActiveReconRunDetailView
): ActiveReconRunSafeReportSnapshot {
  const sections: ActiveReconRunSafeReportSection[] = [];

  // Scope Section
  const scopeEntries = [
    `Run ID: ${detail.summary.runId}`,
    `Target Origin: ${detail.summary.subject.normalizedOrigin ?? 'Unknown'}`,
    `Status: ${detail.summary.status}`
  ];
  sections.push({
    kind: 'scope',
    title: 'Scope',
    entries: scopeEntries
  });

  // Probe Summary Section
  const summaryEntries = [
    `Probes Planned: ${detail.summary.counts.probesPlanned}`,
    `Probes Completed: ${detail.summary.counts.probesCompleted}`,
    `Probes Blocked: ${detail.summary.counts.probesBlocked}`,
    `Probes Failed: ${detail.summary.counts.probesFailed}`,
    `Total Observations: ${detail.summary.counts.observations}`
  ];
  sections.push({
    kind: 'probe_summary',
    title: 'Probe Summary',
    entries: summaryEntries
  });

  // Document Metadata Section
  const metadataEntries: string[] = [];
  if (detail.summary.documentProbeSummary.robots.present) {
    metadataEntries.push('robots.txt metadata was observed.');
  }
  if (detail.summary.documentProbeSummary.securityTxt.present) {
    metadataEntries.push('security.txt metadata was observed.');
  }
  if (metadataEntries.length === 0) {
    metadataEntries.push('No recognized document metadata was observed.');
  }
  sections.push({
    kind: 'document_metadata',
    title: 'Document Metadata',
    entries: metadataEntries
  });

  // Run Errors Section
  if (detail.runErrors.length > 0) {
    const errorEntries = detail.runErrors.map(e => `Error [${e.code}]: ${e.message}`);
    sections.push({
      kind: 'run_errors',
      title: 'Run Errors',
      entries: errorEntries
    });
  }

  // Limitations Section
  const limitationEntries = [
    'The run completed with safe document probe observations only.',
    'No vulnerability findings were generated by this milestone.'
  ];
  sections.push({
    kind: 'limitations',
    title: 'Limitations',
    entries: limitationEntries
  });

  return {
    contractVersion: 'active-recon-run-safe-report/v0',
    reportKind: 'active-recon.safe-run-report',
    title: 'Active Recon Safe Run Report',
    subject: {
      kind: 'origin',
      normalizedOrigin: detail.summary.subject.normalizedOrigin
    },
    run: {
      runId: detail.summary.runId,
      status: detail.summary.status,
      createdAt: detail.summary.timestamps.createdAt,
      updatedAt: detail.summary.timestamps.updatedAt
    },
    sections,
    explicitNonClaims: {
      noFindingsGenerated: true,
      noEvidenceRecordsGenerated: true,
      noVulnerabilitiesConfirmed: true,
      noRiskSeverityOrImpactClaims: true,
      noRawHttpDataIncluded: true
    },
    classification: {
      finding: false,
      evidence: false,
      vulnerability: false,
      riskClaim: false
    }
  };
}
