import type { AuthorizedScope } from '../policy/EgressPolicyContracts.js';
import type { SafeActiveReconObservation } from './ActiveReconContracts.js';

export type ActiveReconOriginRunVersion = 'active-recon-origin-run/v0';

export type ActiveReconOriginProbeSelection =
  | {
      family: 'document';
      probe: 'http.robots.inspect' | 'http.security_txt.inspect';
    };

export type ActiveReconOriginRunRequest = {
  contractVersion: ActiveReconOriginRunVersion;

  // Caller-supplied ID is accepted only for external correlation.
  // It must never be echoed in safe output.
  requestId?: string;

  authorization: {
    confirmed: true;
    scopeLabel?: string;
  };

  authorizedScope: AuthorizedScope;

  origin: string;

  probes: ActiveReconOriginProbeSelection[];
};

export type ActiveReconOriginRunProbeResult = {
  safeProbeIndex: string;

  family: 'document';

  safeKind:
    | 'http.robots.inspect'
    | 'http.security_txt.inspect'
    | 'unknown';

  status:
    | 'planned'
    | 'completed'
    | 'blocked'
    | 'candidate'
    | 'failed';

  target: {
    normalizedOrigin?: string;
    safeDisplayUrl?: string;
  };

  observations: SafeActiveReconObservation[];

  error?: {
    code:
      | 'authorization_not_confirmed'
      | 'invalid_origin'
      | 'origin_out_of_scope'
      | 'unsupported_probe'
      | 'empty_probe_set'
      | 'planning_failed'
      | 'runner_failed'
      | 'adapter_missing'
      | 'adapter_failed'
      | 'policy_blocked'
      | 'policy_candidate';
    message: string;
  };
};

export type ActiveReconOriginRunError = {
  code:
    | 'authorization_not_confirmed'
    | 'invalid_origin'
    | 'origin_out_of_scope'
    | 'unsupported_probe'
    | 'empty_probe_set'
    | 'planning_failed'
    | 'runner_failed';
  message: string;
};

export type ActiveReconOriginRunResult = {
  contractVersion: ActiveReconOriginRunVersion;

  runId: string; // generated by service, never caller-provided

  status: 'completed' | 'partial' | 'failed';

  normalizedOrigin?: string;

  requestedProbeCount: number;
  plannedProbeCount: number;
  completedProbeCount: number;
  blockedProbeCount: number;
  candidateProbeCount: number;
  failedProbeCount: number;

  runErrors: ActiveReconOriginRunError[];

  probes: ActiveReconOriginRunProbeResult[];

  observations: SafeActiveReconObservation[];

  classification: {
    finding: false;
    evidence: false;
    vulnerability: false;
    riskClaim: false;
  };
};
